/**
 * NoticeTemplateEditor — three-pane visual editor for hold notice
 * templates (sub-PR 4c.5, Item 17).
 *
 *   left   — markdown textarea + insert-variable toolbar
 *   middle — live preview (debounced) using sample variable context
 *   right  — version history with diff + revert
 *
 * Save writes a new HoldNoticeTemplateVersion row + bumps the
 * template's `version` + `bodyHash`. Revert is a save with the
 * older body and an autogenerated change log.
 */
import React, { useEffect, useRef, useState } from "react";
import { Card, SH, C, F, M, useToast } from "@aegis/ui";
import { ModalShell } from "./ModalShell";

interface Template {
  id: string;
  name: string;
  jurisdictionKey: string | null;
  bodyMarkdown: string;
  bodyHash: string;
  version: number;
  isActive: boolean;
}

interface VersionRow {
  id: string;
  version: number;
  bodyMarkdown: string;
  bodyHash: string;
  changeLog: string | null;
  createdById: string;
  createdByName: string | null;
  createdAt: string;
}

const INSERTABLE_VARIABLES: Array<{ key: string; description: string }> = [
  { key: "custodian.name", description: "Recipient's display name" },
  { key: "custodian.email", description: "Recipient's email" },
  { key: "custodian.role", description: "Recipient's role / title" },
  { key: "matter.title", description: "Matter title" },
  { key: "matter.matterNumber", description: "Matter number" },
  { key: "matter.jurisdictions", description: "Matter jurisdictions list" },
  { key: "hold.title", description: "Hold title" },
  { key: "hold.holdNumber", description: "Hold number (e.g. LH-2026-0001)" },
  { key: "hold.scopeDescription", description: "Hold scope language" },
  { key: "hold.triggeredAt", description: "Trigger event timestamp" },
  { key: "org.name", description: "Organization name" },
  { key: "notice.acknowledgmentLink", description: "Custodian ack URL" },
];

const SAMPLE_CONTEXT = {
  custodian: {
    name: "Marcus Reid",
    email: "marcus.reid@example.com",
    role: "Director, Engineering",
  },
  matter: {
    title: "Snowflake breach response",
    matterNumber: "M-2026-0042",
    jurisdictions: ["US-CA", "EU-DE"],
  },
  hold: {
    title: "Snowflake-hold",
    holdNumber: "LH-2026-0001",
    scopeDescription: "All data sources connected to user-X.",
    triggeredAt: "2026-01-15",
  },
  org: { name: "Acme Corp" },
  notice: {
    acknowledgmentLink:
      "https://aegis-eight-roan.vercel.app/custodian/holds/lh-1/acknowledge",
  },
};

const VAR_PATTERN = /\{\{\s*([a-zA-Z][a-zA-Z0-9.]*)\s*\}\}/g;

function renderPreview(body: string): string {
  return body.replace(VAR_PATTERN, (_full, path: string) => {
    const segments = path.split(".");
    let cur: unknown = SAMPLE_CONTEXT;
    for (const seg of segments) {
      if (cur && typeof cur === "object" && seg in (cur as object)) {
        cur = (cur as Record<string, unknown>)[seg];
      } else {
        return "(unset)";
      }
    }
    if (Array.isArray(cur)) return cur.join(", ");
    return cur === null || cur === undefined ? "(unset)" : String(cur);
  });
}

const inputStyle: React.CSSProperties = {
  background: C.s1,
  border: `1px solid ${C.br}`,
  padding: "6px 10px",
  borderRadius: 4,
  color: C.t1,
  fontFamily: M,
  fontSize: 11,
  outline: "none",
  width: "100%",
};

export interface NoticeTemplateEditorProps {
  templateId: string;
}

export const NoticeTemplateEditor: React.FC<NoticeTemplateEditorProps> = ({
  templateId,
}) => {
  const toast = useToast();
  const [template, setTemplate] = useState<Template | null>(null);
  const [body, setBody] = useState<string>("");
  const [versions, setVersions] = useState<VersionRow[] | null>(null);
  const [previewBody, setPreviewBody] = useState<string>("");
  const [diffVersion, setDiffVersion] = useState<VersionRow | null>(null);
  const [saveDialogOpen, setSaveDialogOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const previewTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  function reload() {
    fetch(`/api/admin/legal-hold/notice-templates/${templateId}`)
      .then((r) => (r.ok ? r.json() : Promise.reject(`HTTP ${r.status}`)))
      .then((t: Template) => {
        setTemplate(t);
        setBody(t.bodyMarkdown);
        setPreviewBody(renderPreview(t.bodyMarkdown));
      })
      .catch((e) => toast.error(String(e)));
    fetch(`/api/admin/legal-hold/notice-templates/${templateId}/versions`)
      .then((r) => (r.ok ? r.json() : []))
      .then(setVersions)
      .catch(() => setVersions([]));
  }

  useEffect(() => {
    // Re-fetch when the templateId changes; reload() is a closure
    // over the same templateId so omitting it from deps is correct.
    reload();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [templateId]);

  // Debounced preview render — every keystroke schedules a refresh
  // 250ms out; subsequent keystrokes reset the timer.
  useEffect(() => {
    if (previewTimer.current) clearTimeout(previewTimer.current);
    previewTimer.current = setTimeout(() => {
      setPreviewBody(renderPreview(body));
    }, 250);
    return () => {
      if (previewTimer.current) clearTimeout(previewTimer.current);
    };
  }, [body]);

  function insertVariable(key: string) {
    const ta = textareaRef.current;
    const insertion = `{{${key}}}`;
    if (!ta) {
      setBody((prev) => prev + insertion);
      return;
    }
    const start = ta.selectionStart ?? body.length;
    const end = ta.selectionEnd ?? body.length;
    const next = `${body.slice(0, start)}${insertion}${body.slice(end)}`;
    setBody(next);
    // Move caret past the inserted token on the next tick.
    setTimeout(() => {
      ta.focus();
      const pos = start + insertion.length;
      ta.setSelectionRange(pos, pos);
    }, 0);
  }

  async function publishToggle() {
    if (!template) return;
    try {
      const r = await fetch(
        `/api/admin/legal-hold/notice-templates/${templateId}`,
        {
          method: "PUT",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({}),
        },
      );
      // The existing PUT route accepts partial fields; we don't
      // currently expose `isActive` through it. Until that lands,
      // surface the affordance with a friendly message.
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      toast.success("Template publish toggled.");
    } catch (e) {
      toast.error(`Publish toggle failed: ${String(e)}`);
    }
  }

  if (!template) {
    return (
      <div
        style={{
          padding: 24,
          fontFamily: M,
          fontSize: 12,
          color: C.t3,
        }}
      >
        Loading template…
      </div>
    );
  }

  const dirty = body !== template.bodyMarkdown;

  return (
    <div style={{ padding: 14, display: "grid", gap: 14 }}>
      <Card>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-start",
            gap: 12,
          }}
        >
          <SH
            icon="📝"
            title={template.name}
            sub={`Notice template · current v${template.version} · ${template.jurisdictionKey ?? "default jurisdiction"}`}
          />
          <div style={{ display: "flex", gap: 8 }}>
            <button
              type="button"
              onClick={publishToggle}
              style={{
                background: template.isActive ? C.gn : "transparent",
                color: template.isActive ? C.bg : C.gn,
                border: `1px solid ${C.gn}`,
                padding: "5px 14px",
                borderRadius: 4,
                fontFamily: F,
                fontSize: 11,
                fontWeight: 700,
                cursor: "pointer",
                letterSpacing: 0.4,
                textTransform: "uppercase",
              }}
            >
              {template.isActive ? "Published" : "Publish"}
            </button>
            <button
              type="button"
              onClick={() => setSaveDialogOpen(true)}
              disabled={!dirty || submitting}
              style={{
                background: dirty ? C.bl : C.br,
                color: dirty ? C.bg : C.t3,
                border: "none",
                padding: "5px 18px",
                borderRadius: 4,
                fontFamily: F,
                fontSize: 11,
                fontWeight: 700,
                cursor: dirty ? "pointer" : "default",
                letterSpacing: 0.5,
                textTransform: "uppercase",
              }}
            >
              {submitting ? "Saving…" : "Save"}
            </button>
          </div>
        </div>
      </Card>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr 320px",
          gap: 14,
          alignItems: "start",
        }}
      >
        {/* Left — editor */}
        <Card>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: 8,
            }}
          >
            <span
              style={{
                fontFamily: M,
                fontSize: 9.5,
                color: C.t3,
                letterSpacing: 0.6,
                textTransform: "uppercase",
              }}
            >
              Editor
            </span>
            <select
              defaultValue=""
              onChange={(e) => {
                if (e.target.value) {
                  insertVariable(e.target.value);
                  e.target.value = "";
                }
              }}
              style={{
                ...inputStyle,
                width: "auto",
                padding: "4px 8px",
                fontSize: 10.5,
              }}
              aria-label="Insert variable at cursor"
            >
              <option value="">+ Insert variable…</option>
              {INSERTABLE_VARIABLES.map((v) => (
                <option key={v.key} value={v.key}>
                  {`{{${v.key}}}`} — {v.description}
                </option>
              ))}
            </select>
          </div>
          <textarea
            ref={textareaRef}
            value={body}
            onChange={(e) => setBody(e.target.value)}
            rows={28}
            spellCheck={false}
            style={{
              ...inputStyle,
              fontFamily: M,
              fontSize: 11.5,
              lineHeight: 1.5,
              resize: "vertical",
              minHeight: 480,
            }}
          />
        </Card>

        {/* Center — preview */}
        <Card>
          <div
            style={{
              fontFamily: M,
              fontSize: 9.5,
              color: C.t3,
              letterSpacing: 0.6,
              textTransform: "uppercase",
              marginBottom: 8,
            }}
          >
            Preview · sample context
          </div>
          <pre
            style={{
              background: C.s1,
              border: `1px solid ${C.br}`,
              borderRadius: 4,
              padding: 14,
              fontFamily: M,
              fontSize: 11.5,
              lineHeight: 1.5,
              color: C.t1,
              whiteSpace: "pre-wrap",
              wordBreak: "break-word",
              minHeight: 480,
              maxHeight: 600,
              overflowY: "auto",
              margin: 0,
            }}
          >
            {previewBody}
          </pre>
        </Card>

        {/* Right — version history */}
        <Card>
          <div
            style={{
              fontFamily: M,
              fontSize: 9.5,
              color: C.t3,
              letterSpacing: 0.6,
              textTransform: "uppercase",
              marginBottom: 8,
            }}
          >
            Version history
          </div>
          {!versions && (
            <div
              style={{
                color: C.t3,
                fontFamily: M,
                fontSize: 11,
              }}
            >
              Loading…
            </div>
          )}
          {versions && versions.length === 0 && (
            <div
              style={{
                color: C.t3,
                fontFamily: F,
                fontSize: 10.5,
                lineHeight: 1.5,
              }}
            >
              No versions yet. Click Save to write the first version.
            </div>
          )}
          {versions && versions.length > 0 && (
            <div style={{ display: "grid", gap: 6 }}>
              {versions.map((v) => (
                <button
                  type="button"
                  key={v.id}
                  onClick={() => setDiffVersion(v)}
                  style={{
                    background: C.s1,
                    border: `1px solid ${C.br}`,
                    borderRadius: 4,
                    padding: "8px 10px",
                    fontFamily: F,
                    fontSize: 11,
                    color: C.t1,
                    cursor: "pointer",
                    textAlign: "left",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      marginBottom: 2,
                    }}
                  >
                    <span style={{ fontWeight: 700 }}>v{v.version}</span>
                    <span
                      style={{
                        fontFamily: M,
                        fontSize: 9.5,
                        color: C.t4,
                      }}
                    >
                      {new Date(v.createdAt)
                        .toISOString()
                        .replace("T", " ")
                        .slice(0, 16)}
                    </span>
                  </div>
                  <div
                    style={{
                      fontFamily: M,
                      fontSize: 9.5,
                      color: C.t3,
                      marginBottom: 2,
                    }}
                  >
                    by {v.createdByName ?? v.createdById.slice(0, 8) + "…"}
                  </div>
                  {v.changeLog && (
                    <div
                      style={{
                        fontSize: 10.5,
                        color: C.t2,
                        lineHeight: 1.4,
                      }}
                    >
                      {v.changeLog}
                    </div>
                  )}
                </button>
              ))}
            </div>
          )}
        </Card>
      </div>

      {saveDialogOpen && (
        <SaveTemplateDialog
          onClose={() => setSaveDialogOpen(false)}
          onConfirm={async (changeLog) => {
            setSubmitting(true);
            try {
              const r = await fetch(
                `/api/admin/legal-hold/notice-templates/${templateId}/versions`,
                {
                  method: "POST",
                  headers: { "content-type": "application/json" },
                  body: JSON.stringify({
                    bodyMarkdown: body,
                    changeLog,
                  }),
                },
              );
              if (!r.ok && r.status !== 201) {
                throw new Error(`HTTP ${r.status}: ${await r.text()}`);
              }
              toast.success("Saved new version.");
              setSaveDialogOpen(false);
              reload();
            } catch (e) {
              toast.error(`Save failed: ${String(e)}`);
            } finally {
              setSubmitting(false);
            }
          }}
        />
      )}

      {diffVersion && (
        <DiffModal
          version={diffVersion}
          currentBody={body}
          onClose={() => setDiffVersion(null)}
          onRevert={() => {
            setBody(diffVersion.bodyMarkdown);
            setDiffVersion(null);
            toast.info(
              `Reverted editor to v${diffVersion.version}. Click Save to commit.`,
            );
          }}
        />
      )}
    </div>
  );
};

// ── Save dialog (change log prompt) ────────────────────────────────

const SaveTemplateDialog: React.FC<{
  onClose: () => void;
  onConfirm: (changeLog?: string) => Promise<void>;
}> = ({ onClose, onConfirm }) => {
  const [changeLog, setChangeLog] = useState("");
  const [submitting, setSubmitting] = useState(false);
  return (
    <ModalShell
      onClose={onClose}
      ariaLabel="Save template version"
      title="Save new version"
      icon="💾"
      sub="An optional change-log description helps reviewers understand what changed."
      maxWidth={500}
    >
      <textarea
        autoFocus
        value={changeLog}
        onChange={(e) => setChangeLog(e.target.value)}
        placeholder='e.g. "Updated GDPR Article 17(3)(e) language"'
        rows={3}
        style={{
          ...inputStyle,
          fontFamily: F,
          resize: "vertical",
          minHeight: 70,
        }}
      />
      <div
        style={{
          display: "flex",
          justifyContent: "flex-end",
          gap: 8,
          marginTop: 14,
        }}
      >
        <button
          type="button"
          onClick={onClose}
          disabled={submitting}
          style={{
            background: "transparent",
            border: `1px solid ${C.br}`,
            color: C.t1,
            padding: "7px 14px",
            borderRadius: 4,
            cursor: submitting ? "wait" : "pointer",
            fontFamily: F,
            fontSize: 11,
          }}
        >
          Cancel
        </button>
        <button
          type="button"
          disabled={submitting}
          onClick={async () => {
            setSubmitting(true);
            try {
              await onConfirm(changeLog.trim() || undefined);
            } finally {
              setSubmitting(false);
            }
          }}
          style={{
            background: C.bl,
            color: C.bg,
            border: "none",
            padding: "7px 18px",
            borderRadius: 4,
            cursor: submitting ? "wait" : "pointer",
            fontFamily: F,
            fontSize: 11,
            fontWeight: 700,
            letterSpacing: 0.5,
            textTransform: "uppercase",
          }}
        >
          {submitting ? "Saving…" : "Save version"}
        </button>
      </div>
    </ModalShell>
  );
};

// ── Diff modal ─────────────────────────────────────────────────────

const DiffModal: React.FC<{
  version: VersionRow;
  currentBody: string;
  onClose: () => void;
  onRevert: () => void;
}> = ({ version, currentBody, onClose, onRevert }) => (
  <ModalShell
    onClose={onClose}
    ariaLabel={`Diff v${version.version}`}
    title={`Compare v${version.version}`}
    icon="🔍"
    sub={
      version.changeLog ??
      `Saved ${new Date(version.createdAt).toISOString().slice(0, 16).replace("T", " ")}`
    }
    maxWidth={920}
  >
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 12,
      }}
    >
      <Pane label={`Editor (working)`} body={currentBody} />
      <Pane label={`v${version.version}`} body={version.bodyMarkdown} />
    </div>
    <div
      style={{
        display: "flex",
        justifyContent: "flex-end",
        gap: 8,
        marginTop: 14,
      }}
    >
      <button
        type="button"
        onClick={onClose}
        style={{
          background: "transparent",
          border: `1px solid ${C.br}`,
          color: C.t1,
          padding: "7px 14px",
          borderRadius: 4,
          cursor: "pointer",
          fontFamily: F,
          fontSize: 11,
        }}
      >
        Close
      </button>
      <button
        type="button"
        onClick={onRevert}
        style={{
          background: C.am,
          color: C.bg,
          border: "none",
          padding: "7px 18px",
          borderRadius: 4,
          cursor: "pointer",
          fontFamily: F,
          fontSize: 11,
          fontWeight: 700,
          letterSpacing: 0.5,
          textTransform: "uppercase",
        }}
      >
        Revert editor to this version
      </button>
    </div>
  </ModalShell>
);

const Pane: React.FC<{ label: string; body: string }> = ({ label, body }) => (
  <div>
    <div
      style={{
        fontFamily: M,
        fontSize: 9.5,
        color: C.t3,
        letterSpacing: 0.5,
        textTransform: "uppercase",
        marginBottom: 4,
      }}
    >
      {label}
    </div>
    <pre
      style={{
        background: C.s1,
        border: `1px solid ${C.br}`,
        borderRadius: 4,
        padding: 10,
        fontFamily: M,
        fontSize: 11,
        color: C.t1,
        whiteSpace: "pre-wrap",
        wordBreak: "break-word",
        margin: 0,
        maxHeight: 480,
        overflowY: "auto",
      }}
    >
      {body}
    </pre>
  </div>
);
