// v7.2 seed — copied verbatim (so existing demos still work), ages in hours
export const V72_SEED=[
{id:"REQ-3401",_source:"seed",_ageHours:2.23,from:"Sarah Johnson",dept:"Product",type:"Contract Review",priority:"High",submitted:"2026-04-17 09:14",sla:"24 hrs",slaHours:24,slaStatus:"On Track",
 desc:"New vendor agreement with DataStream AI for ML training data. $800K annual. Need review before Thursday board meeting.",
 assigned:"Maria Chen, Commercial",status:"In Review",stage:"review",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",done:true},{label:"Assigned",done:true},{label:"In Review",active:true},{label:"Complete"}],
 aiTriage:{category:"Vendor Agreement",riskFlag:"Medium — data processing terms need GDPR review",suggestedAssignee:"Commercial Contracts Team",estimatedHours:4,similarMatters:12,confidence:94,routingRule:"RULE-7: Contracts > $500K → Commercial + GDPR check",source:"regex"}},
{id:"REQ-3402",_source:"seed",_ageHours:0.96,from:"Mike Peters",dept:"Engineering",type:"IP Question",priority:"Medium",submitted:"2026-04-17 10:30",sla:"48 hrs",slaHours:48,slaStatus:"On Track",
 desc:"Can we open-source our internal logging framework? Need to check if any patents or trade secrets are implicated.",
 assigned:"David Park, IP Lead",status:"Assigned",stage:"assigned",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",done:true},{label:"Assigned",done:true},{label:"In Review"},{label:"Complete"}],
 aiTriage:{category:"IP / Open Source",riskFlag:"Low — standard OSS assessment",suggestedAssignee:"IP Team",estimatedHours:3,similarMatters:8,confidence:88,routingRule:"RULE-3: IP questions → IP Team lead",source:"regex"}},
{id:"REQ-3403",_source:"seed",_ageHours:6.46,from:"Lisa Wang",dept:"HR",type:"Employment Issue",priority:"Critical",submitted:"2026-04-17 05:00",sla:"4 hrs",slaHours:4,slaStatus:"Overdue",
 desc:"Employee harassment complaint filed against VP Engineering. Plaintiff lawyer contacted HR directly. Need immediate guidance.",
 assigned:"Rachel Adams, Employment",status:"Escalated to GC",stage:"review",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",done:true},{label:"Escalated",done:true},{label:"GC Review",active:true},{label:"Action Plan"}],
 aiTriage:{category:"Employment — Harassment",riskFlag:"Critical — external counsel contact + VP-level respondent",suggestedAssignee:"Employment Team + GC",estimatedHours:20,similarMatters:3,confidence:99,routingRule:"RULE-1: Harassment + VP+ → Auto-escalate to GC",source:"regex"}},
{id:"REQ-3404",_source:"seed",_ageHours:0.71,from:"Tom Bradley",dept:"Procurement",type:"NDA Request",priority:"Low",submitted:"2026-04-17 11:45",sla:"8 hrs",slaHours:8,slaStatus:"On Track",
 desc:"Standard mutual NDA needed for preliminary discussions with Accenture regarding potential consulting engagement.",
 assigned:"AI Auto-Draft",status:"Auto-Completed",stage:"complete",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",done:true},{label:"Auto-Draft",done:true},{label:"Sent to Requester",done:true},{label:"Complete",done:true}],
 aiTriage:{category:"NDA — Standard Mutual",riskFlag:"None — matches standard template 100%",suggestedAssignee:"Auto-Draft Agent",estimatedHours:0,similarMatters:142,confidence:100,routingRule:"RULE-0: Standard NDA → Auto-draft from playbook",source:"regex"}},
{id:"REQ-3405",_source:"seed",_ageHours:3.96,from:"Elena Rossi",dept:"Sales — EU",type:"Compliance Question",priority:"High",submitted:"2026-04-17 07:30",sla:"12 hrs",slaHours:12,slaStatus:"On Track",
 desc:"Client in Germany asking if our AI product complies with EU AI Act. Need a client-ready compliance statement by tomorrow.",
 assigned:"Elena Kraft, EU Counsel",status:"In Review",stage:"review",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",done:true},{label:"Assigned",done:true},{label:"Drafting",active:true},{label:"GC Approval"},{label:"Complete"}],
 aiTriage:{category:"Regulatory — EU AI Act",riskFlag:"High — client-facing statement requires GC approval",suggestedAssignee:"EU Regulatory Team",estimatedHours:6,similarMatters:5,confidence:92,routingRule:"RULE-4: EU regulatory + client-facing → EU Counsel + GC approval",source:"regex"}},
{id:"REQ-3406",_source:"seed",_ageHours:19.46,from:"Carlos Mendez",dept:"Procurement LATAM",type:"Vendor Due Diligence",priority:"Medium",submitted:"2026-04-16 16:00",sla:"72 hrs",slaHours:72,slaStatus:"On Track",
 desc:"New logistics vendor in Brazil — need sanctions screening, anti-bribery due diligence, and compliance sign-off before onboarding.",
 assigned:"Compliance Team",status:"Screening",stage:"triage",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",done:true},{label:"Sanctions Screen",done:true},{label:"DD Review",active:true},{label:"Sign-off"}],
 aiTriage:{category:"Vendor DD — High-Risk Jurisdiction",riskFlag:"Medium — Brazil vendor requires enhanced due diligence per policy",suggestedAssignee:"Compliance + Procurement Legal",estimatedHours:8,similarMatters:24,confidence:90,routingRule:"RULE-5: Vendor DD + LATAM → Compliance (enhanced)",source:"regex"}},
{id:"REQ-3407",_source:"seed",_ageHours:0.46,from:"Auto — Slack Bot",dept:"Finance",type:"Contract Question",priority:"Low",submitted:"2026-04-17 12:00",sla:"24 hrs",slaHours:24,slaStatus:"On Track",
 desc:"When does our SAP license renewal deadline hit? Finance needs for Q2 budget planning.",
 assigned:"AI Auto-Answer",status:"Auto-Completed",stage:"complete",seeded:true,
 workflow:[{label:"Received",done:true},{label:"AI Answer",done:true},{label:"Verified",done:true},{label:"Delivered",done:true},{label:"Complete",done:true}],
 aiTriage:{category:"Contract Query — Informational",riskFlag:"None — factual lookup from contract database",suggestedAssignee:"Knowledge Graph Auto-Answer",estimatedHours:0,similarMatters:89,confidence:100,routingRule:"RULE-0: Informational lookup → Auto-answer from Brain",source:"regex"}},
{id:"REQ-3408",_source:"seed",_ageHours:2.71,from:"Priya Nair",dept:"Marketing",type:"Trademark Check",priority:"Medium",submitted:"2026-04-17 08:45",sla:"24 hrs",slaHours:24,slaStatus:"On Track",
 desc:"Need clearance on 'AegisFlow' as product name — US + EU + India. Launch planned for June.",
 assigned:"David Park, IP Lead",status:"Triage",stage:"triage",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",active:true},{label:"Assigned"},{label:"In Review"},{label:"Complete"}],
 aiTriage:{category:"IP — Trademark Clearance",riskFlag:"Low — routine clearance search",suggestedAssignee:"IP Team",estimatedHours:2,similarMatters:34,confidence:96,routingRule:"RULE-3: IP questions → IP Team lead",source:"regex"}},
{id:"REQ-3409",_source:"seed",_ageHours:5.22,from:"Jens Becker",dept:"Finance DE",type:"Contract Review",priority:"Critical",submitted:"2026-04-17 06:15",sla:"8 hrs",slaHours:8,slaStatus:"At Risk",
 desc:"Emergency — Deutsche Bank loan covenant amendment. €450M facility. CFO presenting to board tomorrow 9am Berlin.",
 assigned:"Unassigned",status:"Triage",stage:"new",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",active:true},{label:"Assigned"},{label:"In Review"},{label:"Complete"}],
 aiTriage:{category:"Finance — Debt Covenant",riskFlag:"Critical — board-deadline + €450M exposure",suggestedAssignee:"Finance Legal + GC",estimatedHours:10,similarMatters:4,confidence:97,routingRule:"RULE-2: Debt > €100M → Finance Legal + GC review",source:"regex"}},
{id:"REQ-3410",_source:"seed",_ageHours:1.43,from:"Karen Liu",dept:"Product",type:"Privacy Question",priority:"Medium",submitted:"2026-04-17 10:02",sla:"24 hrs",slaHours:24,slaStatus:"On Track",
 desc:"Adding device telemetry to mobile app. Need DPIA if we collect IMEI + approximate location for diagnostic purposes?",
 assigned:"Privacy Team",status:"Assigned",stage:"assigned",seeded:true,
 workflow:[{label:"Submitted",done:true},{label:"AI Triage",done:true},{label:"Assigned",done:true},{label:"In Review"},{label:"Complete"}],
 aiTriage:{category:"Privacy — DPIA",riskFlag:"Medium — device identifiers may constitute personal data under GDPR",suggestedAssignee:"Privacy Team",estimatedHours:5,similarMatters:18,confidence:91,routingRule:"RULE-6: Privacy / DPIA → Privacy Team",source:"regex"}},
];
