/**
 * Notice template version history (sub-PR 4c.5, Item 17).
 *
 * Every template save writes one HoldNoticeTemplateVersion row. The
 * template's `version` + `bodyHash` mirror the latest version's
 * fields so the existing notice composer flow doesn't need to
 * change. Older HoldNoticeIssuance rows resolve their own body
 * by joining `(templateId, version)` against this table.
 *
 * Save semantics:
 *   - First save when no versions exist → write v1 with the
 *     template's current body (snapshot of the legacy state)
 *     before writing the user's new revision as v2.
 *   - Subsequent saves → bump version monotonically.
 *   - Reverting to an older version is just "save with that
 *     body and an autogenerated changeLog like 'Revert to v3'".
 */
import {
  bodyHash as computeHash,
  logAudit,
  prisma,
  type HoldNoticeTemplateVersion,
} from "@aegis/db";

export interface VersionDTO {
  id: string;
  version: number;
  bodyMarkdown: string;
  bodyHash: string;
  changeLog: string | null;
  createdById: string;
  createdByName: string | null;
  createdAt: string;
}

interface AdminActor {
  id: string;
  organizationId: string;
}

export async function listTemplateVersionsService(
  templateId: string,
  actor: AdminActor,
): Promise<VersionDTO[]> {
  const tpl = await prisma.holdNoticeTemplate.findFirst({
    where: { id: templateId, organizationId: actor.organizationId },
    select: { id: true },
  });
  if (!tpl) throw new Error(`Template ${templateId} not found`);
  const rows = await prisma.holdNoticeTemplateVersion.findMany({
    where: { templateId },
    include: { createdBy: { select: { name: true } } },
    orderBy: [{ version: "desc" }],
  });
  return rows.map(toDTO);
}

export interface SaveTemplateVersionInput {
  templateId: string;
  bodyMarkdown: string;
  changeLog?: string;
}

/**
 * Save a new version. Returns the created version row plus the
 * updated template (with bumped version + bodyHash).
 */
export async function saveTemplateVersionService(
  input: SaveTemplateVersionInput,
  actor: AdminActor,
): Promise<{
  version: VersionDTO;
  templateVersion: number;
  templateBodyHash: string;
}> {
  if (!input.bodyMarkdown || input.bodyMarkdown.length === 0) {
    throw new Error("bodyMarkdown required");
  }
  const tpl = await prisma.holdNoticeTemplate.findFirst({
    where: { id: input.templateId, organizationId: actor.organizationId },
  });
  if (!tpl) throw new Error(`Template ${input.templateId} not found`);

  // Bootstrap: if no version row exists yet, snapshot the current
  // template body as v1 (preserves history for any pre-4c.5
  // issuances) before writing the new revision.
  const existingCount = await prisma.holdNoticeTemplateVersion.count({
    where: { templateId: tpl.id },
  });

  const newHash = computeHash(input.bodyMarkdown);
  const next = existingCount === 0 ? tpl.version + 1 : tpl.version + 1;

  const created = await prisma.$transaction(async (tx) => {
    if (existingCount === 0) {
      await tx.holdNoticeTemplateVersion.create({
        data: {
          templateId: tpl.id,
          version: tpl.version,
          bodyMarkdown: tpl.bodyMarkdown,
          bodyHash: tpl.bodyHash,
          changeLog: "Initial version (auto-snapshotted on first save)",
          createdById: actor.id,
        },
      });
    }
    const v = await tx.holdNoticeTemplateVersion.create({
      data: {
        templateId: tpl.id,
        version: next,
        bodyMarkdown: input.bodyMarkdown,
        bodyHash: newHash,
        changeLog: input.changeLog?.trim() || null,
        createdById: actor.id,
      },
      include: { createdBy: { select: { name: true } } },
    });
    await tx.holdNoticeTemplate.update({
      where: { id: tpl.id },
      data: {
        bodyMarkdown: input.bodyMarkdown,
        bodyHash: newHash,
        version: next,
      },
    });
    return v;
  });

  await logAudit({
    organizationId: actor.organizationId,
    actorId: actor.id,
    actorType: "USER",
    action: "matter.legal_hold.notice_template.version_saved",
    resourceType: "HoldNoticeTemplate",
    resourceId: tpl.id,
    afterJson: {
      version: created.version,
      bodyHash: created.bodyHash,
      changeLog: created.changeLog,
    },
  });

  return {
    version: toDTO(created),
    templateVersion: next,
    templateBodyHash: newHash,
  };
}

export async function getTemplateVersionByNumberService(
  templateId: string,
  version: number,
  actor: AdminActor,
): Promise<VersionDTO | null> {
  const tpl = await prisma.holdNoticeTemplate.findFirst({
    where: { id: templateId, organizationId: actor.organizationId },
    select: { id: true },
  });
  if (!tpl) return null;
  const row = await prisma.holdNoticeTemplateVersion.findUnique({
    where: { templateId_version: { templateId, version } },
    include: { createdBy: { select: { name: true } } },
  });
  return row ? toDTO(row) : null;
}

function toDTO(
  row: HoldNoticeTemplateVersion & { createdBy?: { name: string } | null },
): VersionDTO {
  return {
    id: row.id,
    version: row.version,
    bodyMarkdown: row.bodyMarkdown,
    bodyHash: row.bodyHash,
    changeLog: row.changeLog,
    createdById: row.createdById,
    createdByName: row.createdBy?.name ?? null,
    createdAt: row.createdAt.toISOString(),
  };
}
