// ── Agent knowledge base (FAQ agent) ──
// First trigger match wins; existing entries stay first so prior routing
// is unchanged. New entries are ordered specific → general within their
// block. Expanded in Intake P2b from 6 → 26 to lift real deflection
// coverage past the demo seed.
export const AGENT_KB=[
  {q:"Can I share this document with a vendor?",triggers:[/share|disclose|send.*document/],answer:"Yes, if the vendor has a signed NDA on file (check Brain) and the document is not marked Highly Confidential. For Highly Confidential, use the clean-room workflow.",source:"Playbook § 3.1"},
  {q:"What's our standard MSA payment term?",triggers:[/payment.{0,10}term|net.{0,3}(30|45|60)/],answer:"Net 45 from receipt of invoice. Net 30 only if counterparty offers ≥2% prompt-pay discount. Anything shorter requires VP Finance approval.",source:"Playbook § 2.4"},
  {q:"Do I need legal review for a standard NDA?",triggers:[/\bnda\b|non.{0,3}disclosure/],answer:"No. Use the Self-Serve NDA generator — it picks the right template (mutual/one-way/evaluation) and auto-fills counterparty info. Only escalate if there are non-standard clauses.",source:"Playbook § 1.2"},
  {q:"When does our vendor contract with [X] expire?",triggers:[/\bexpir|renewal.{0,10}date|when.{0,10}(does|will).{0,20}expire/],answer:"Aurora reads the contract registry and returns expiry, renewal terms, and current notice period.",source:"Contract Registry"},
  {q:"Is this vendor on any sanctions list?",triggers:[/sanction|ofac|denied party/],answer:"Paste vendor legal name into the Sanctions Screen widget — checks OFAC, EU, UK, UN lists in real time.",source:"Sanctions Screen"},
  {q:"What's our data retention period for customer data?",triggers:[/retention|retain.*data|how long.*keep/],answer:"7 years from contract termination, except EU (3 years + 2 years warranty). Financial records: 10 years per SOX.",source:"Privacy Notice § 7"},

  // ── Contract terms ──
  {q:"What's our standard limitation of liability cap?",triggers:[/limitation.{0,5}of.{0,5}liability|liability.{0,5}cap|cap.{0,10}(damages|liability)/],answer:"Default cap = 12 months' fees paid. Carve-outs (uncapped): IP infringement, breach of confidentiality, indemnity obligations, gross negligence/willful misconduct. A super-cap (e.g. 2x) may be negotiated for high-value deals with VP Legal sign-off.",source:"Contract Playbook § 4.1"},
  {q:"What indemnification do we accept as standard?",triggers:[/indemnif|hold.{0,5}harmless|defend.{0,10}claim/],answer:"Mutual indemnity for third-party claims arising from the indemnifying party's breach, IP infringement, or negligence. We do NOT accept unlimited or first-party indemnities. Indemnity is carved out of the liability cap.",source:"Contract Playbook § 4.2"},
  {q:"What's our default governing law and venue?",triggers:[/governing.{0,5}law|choice.{0,5}of.{0,5}law|jurisdiction.{0,10}clause|\bvenue\b/],answer:"Delaware law, Delaware courts (or Delaware-seated arbitration for international counterparties). Acceptable alternatives: New York, California. Avoid the counterparty's home jurisdiction for non-US entities.",source:"Contract Playbook § 6.1"},
  {q:"Are auto-renewal / evergreen terms OK?",triggers:[/auto.{0,5}renew|evergreen|automatic.{0,5}renewal/],answer:"Acceptable if the non-renewal notice window is ≤60 days and renewal price increase is capped (see price-increase guidance). Flag any evergreen with >60-day notice or uncapped uplift for review.",source:"Contract Playbook § 2.7"},
  {q:"What termination-for-convenience notice do we require?",triggers:[/terminat.{0,15}(convenience|without cause)|exit.{0,5}clause/],answer:"We want the right to terminate for convenience on 30 days' written notice. For vendor contracts, 30–90 days is acceptable. Pure term-locked deals with no convenience exit require VP approval.",source:"Contract Playbook § 5.1"},
  {q:"What's the cap on annual price increases?",triggers:[/price.{0,10}increase|uplift|annual.{0,5}escalat|cpi.{0,5}adjust/],answer:"Renewal price increases capped at the lesser of 5% or CPI. Uncapped or >5% uplifts must be flagged. Multi-year prepay should lock pricing for the term.",source:"Contract Playbook § 2.8"},
  {q:"What SLA / uptime should we require from SaaS vendors?",triggers:[/\bsla\b|uptime|service.{0,5}level|availability.{0,5}(commit|guarantee)/],answer:"Minimum 99.9% monthly uptime with service credits for misses. Mission-critical systems: 99.95%+. Credits are a remedy, not the sole remedy — preserve termination rights for chronic breach.",source:"Vendor Playbook § 3.4"},
  {q:"What insurance do we require from vendors?",triggers:[/insurance|coverage.{0,10}require|certificate.{0,5}of.{0,5}insurance|\bcoi\b/],answer:"Standard: $1M/$2M commercial general liability, $1M professional liability (E&O), and cyber liability for data processors ($2M+). We must be named as additional insured. Request a COI before onboarding.",source:"Vendor Playbook § 4.1"},
  {q:"When is a Data Processing Agreement (DPA) required?",triggers:[/\bdpa\b|data.{0,5}processing.{0,5}(agreement|addendum)|processor.{0,5}agreement/],answer:"Required whenever a vendor processes personal data on our behalf (GDPR Art. 28 / CCPA service-provider terms). Use our standard DPA v3.1. Sub-processors require prior written approval and a flow-down DPA.",source:"Privacy Playbook § 2.1"},
  {q:"How long should a confidentiality obligation survive?",triggers:[/confidential.{0,15}(term|surviv|period|duration)|how long.{0,10}confidential/],answer:"Standard NDA term: 2 years from disclosure (3–5 years for technical/source-code material). Trade secrets remain protected indefinitely while they qualify as trade secrets. Avoid perpetual blanket confidentiality.",source:"Contract Playbook § 1.5"},
  {q:"Can the counterparty assign the contract or on change of control?",triggers:[/\bassign(ment)?\b|change.{0,5}of.{0,5}control|novation/],answer:"No assignment without our prior written consent, except we permit assignment to an affiliate or successor in a merger/acquisition. We retain a termination right on the counterparty's change of control to a competitor.",source:"Contract Playbook § 7.2"},
  {q:"What warranty and acceptance period is standard?",triggers:[/warrant|acceptance.{0,5}(test|period)|defect.{0,5}period/],answer:"90-day warranty that deliverables conform to spec; 30-day acceptance window with a right to reject non-conforming work. Avoid 'AS-IS' for paid deliverables.",source:"Contract Playbook § 3.6"},

  // ── IP / open source / export ──
  {q:"Who owns work product a contractor creates for us?",triggers:[/work.{0,5}product|own.{0,10}(ip|work|deliverable)|work.{0,5}for.{0,5}hire|assignment.{0,5}of.{0,5}ip/],answer:"We require a present-tense assignment of all IP in deliverables ('hereby assigns'), plus a waiver of moral rights and a license-back for the contractor's pre-existing/background IP. 'Work made for hire' alone is insufficient for patents — always include the assignment.",source:"IP Playbook § 1.1"},
  {q:"Can we use this open-source library in our product?",triggers:[/open.{0,5}source|\bgpl\b|\bmit\b|apache.{0,5}license|\blgpl\b|copyleft/],answer:"Permissive licenses (MIT, Apache-2.0, BSD) are pre-approved for most use. Copyleft (GPL/LGPL/AGPL) requires review — AGPL is generally prohibited in our SaaS. Log all dependencies in the OSS register and preserve license/notice files.",source:"IP Playbook § 4.2"},
  {q:"Do export controls apply to sharing this technology?",triggers:[/export.{0,5}(control|compliance)|\bear\b|\bitar\b|dual.{0,5}use|deemed.{0,5}export/],answer:"Most commercial software is EAR99 (low restriction) but encryption and any defense-related tech can be controlled. Sharing controlled tech with a foreign national — even internally — can be a 'deemed export.' Screen the destination/recipient and consult Legal before transfer to restricted countries.",source:"Trade Compliance § 2"},

  // ── Vendor / procurement ──
  {q:"Do we need to approve a vendor's sub-processors?",triggers:[/sub.{0,5}processor|subcontractor.{0,10}(data|approv)|fourth.{0,5}party/],answer:"Yes for any party processing our personal data. Require an up-to-date sub-processor list, prior notice of additions with an objection right, and DPA flow-down terms. No undisclosed sub-processors.",source:"Privacy Playbook § 2.3"},
  {q:"Can a vendor use our name or logo publicly?",triggers:[/logo|publicity|press.{0,5}release|marketing.{0,5}use|use.{0,5}our.{0,5}name|case.{0,5}study/],answer:"No use of our name, logo, or a case study without prior written approval per use. We may grant a limited customer-list listing right. Strike blanket publicity rights from vendor templates.",source:"Brand & Legal Policy § 3"},
  {q:"What's our policy on most-favored-nation (MFN) pricing clauses?",triggers:[/most.{0,5}favored|\bmfn\b|best.{0,5}price.{0,5}(guarantee|clause)/],answer:"We seek MFN on price from strategic vendors; we resist granting MFN as a seller (it constrains future deals and raises antitrust questions in some contexts). Flag any MFN we'd be granting for Legal review.",source:"Contract Playbook § 2.9"},

  // ── Process ──
  {q:"How do I escalate an urgent contract that needs signing today?",triggers:[/urgent|rush|need.{0,10}(today|asap)|expedite/],answer:"Mark the intake ticket priority Critical and note the deadline in the description. The routing engine fast-lanes Critical items to the GC with a 4-hour SLA. For true same-hour needs, also ping the #legal-urgent channel.",source:"Intake Playbook § 1.4"},
];

export function matchAgentKB(text){
  const t=(text||"").toLowerCase();
  for(const item of AGENT_KB){
    if(item.triggers.some(re=>re.test(t))) return item;
  }
  return null;
}
